apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: todo-johannes
  name: view-secrets
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get"]
