apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-app-monitor
  name: prometheus-app-monitor
  namespace: todo-johannes
spec:
  endpoints:
    - interval: 30s
      targetPort: 7001
      path: /q/metrics
      scheme: http
  selector:
    matchLabels:
      app-with-metrics: 'todo-api'